# Generated by Django 3.2.4 on 2021-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0002_auto_20210606_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed',
            field=models.ManyToManyField(blank=True, default=None, related_name='viewed', to='products.Product'),
        ),
    ]
